### Get all pizzas
GET http://localhost:5257/api/pizzas

### Get a specific pizza
GET http://localhost:5257/api/pizzas/1

### Create a new pizza
POST http://localhost:5257/api/pizzas
Content-Type: application/json

{
  "name": "Margherita",
  "isGlutenFree": false
}

### Update an existing pizza
PUT http://localhost:5257/api/pizzas/1
Content-Type: application/json

{
  "name": "Updated Pepperoni",
  "isGlutenFree": true
}

### Delete a pizza
DELETE http://localhost:5257/api/pizzas/1
